<a href="https://colab.research.google.com/github/Jamieho1602/IBM-HR-Analytics-Overview/blob/main/IBM_HR_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

employees = pd.read_csv('/content/drive/MyDrive/IBM HR Analytics/Employees.csv')

employees.head()

,EmployeeNumber,Age,Gender,MaritalStatus,Education,EducationField,Department,JobRole,JobLevel,BusinessTravel,DistanceFromHome,EmployeeCount,Over18,StandardHours
0,1,41.0,Female,Single,2,Life Sciences,Sales,Sales Executive,2,Travel_Rarely,1,1,Y,80
1,2,49.0,Male,Married,1,Life Sciences,Research & Development,Research Scientist,2,Travel_Frequently,8,1,Y,80
2,4,37.0,Male,Single,2,Other,Research & Development,Laboratory Technician,1,Travel_Rarely,2,1,Y,80
3,5,33.0,Female,Married,4,Life Sciences,Research & Development,Research Scientist,1,Travel_Frequently,3,1,Y,80
4,7,27.0,Male,Married,1,Medical,Research & Development,Laboratory Technician,1,Travel_Rarely,2,1,Y,80

In [3]:
compensation = pd.read_csv('/content/drive/MyDrive/IBM HR Analytics/Compensation.csv')

performance = pd.read_csv('/content/drive/MyDrive/IBM HR Analytics/Performance.csv')

experience = pd.read_csv('/content/drive/MyDrive/IBM HR Analytics/Experience.csv')

employment_status = pd.read_csv('/content/drive/MyDrive/IBM HR Analytics/Employment Status.csv')

In [5]:
print("Employees:", employees.shape)
print("Compensation:", compensation.shape)
print("Performance:", performance.shape)
print("Experience:", experience.shape)
print("Employment Status:", employment_status.shape)

Employees: (1470, 14)
Compensation: (1470, 7)
Performance: (1470, 7)
Experience: (1470, 8)
Employment Status: (1470, 3)

In [6]:
print("Employees Missing Values")
print(employees.isnull().sum())

print("Compensation Missing Values")
print(compensation.isnull().sum())

print("Performance Missing Values")
print(performance.isnull().sum())

print("Experience Missing Values")
print(experience.isnull().sum())

print("Employment Status Missing Values")
print(employment_status.isnull().sum())

Employees Missing Values
EmployeeNumber      0
Age                 5
Gender              0
MaritalStatus       0
Education           0
EducationField      0
Department          0
JobRole             0
JobLevel            0
BusinessTravel      0
DistanceFromHome    0
EmployeeCount       0
Over18              0
StandardHours       0
dtype: int64
Compensation Missing Values
EmployeeNumber       0
DailyRate            0
HourlyRate           0
MonthlyIncome        0
MonthlyRate          0
PercentSalaryHike    0
StockOptionLevel     0
dtype: int64
Performance Missing Values
EmployeeNumber              0
PerformanceRating           0
EnvironmentSatisfaction     0
JobInvolvement              0
JobSatisfaction             0
RelationshipSatisfaction    0
WorkLifeBalance             0
dtype: int64
Experience Missing Values
EmployeeNumber             0
NumCompaniesWorked         0
TotalWorkingYears          0
TrainingTimesLastYear      0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64
Employment Status Missing Values
EmployeeNumber    0
Attrition         0
OverTime          0
dtype: int64

In [7]:
employees[employees['Age'].isnull()]

,EmployeeNumber,Age,Gender,MaritalStatus,Education,EducationField,Department,JobRole,JobLevel,BusinessTravel,DistanceFromHome,EmployeeCount,Over18,StandardHours
5,8,NaN,Male,Single,2,Life Sciences,Research & Development,Laboratory Technician,1,Travel_Frequently,2,1,Y,80
27,35,NaN,Male,Married,4,Marketing,Sales,Sales Executive,2,Travel_Rarely,8,1,Y,80
134,177,NaN,Female,Married,1,Life Sciences,Human Resources,Human Resources,1,Travel_Rarely,25,1,Y,80
262,362,NaN,Male,Single,1,Technical Degree,Research & Development,Laboratory Technician,2,Travel_Rarely,2,1,Y,80
377,501,NaN,Female,Married,3,Life Sciences,Research & Development,Research Scientist,1,Travel_Rarely,2,1,Y,80

In [8]:
employees = employees.dropna(subset=['Age'])

employees.shape

(1465, 14)

In [9]:
compensation = compensation[compensation['EmployeeNumber'].isin(employees['EmployeeNumber'])]

performance = performance[performance['EmployeeNumber'].isin(employees['EmployeeNumber'])]

experience = experience[experience['EmployeeNumber'].isin(employees['EmployeeNumber'])]

employment_status = employment_status[employment_status['EmployeeNumber'].isin(employees['EmployeeNumber'])]

In [10]:
print("Employees:", employees.shape)
print("Compensation:", compensation.shape)
print("Performance:", performance.shape)
print("Experience:", experience.shape)
print("Employment Status:", employment_status.shape)

Employees: (1465, 14)
Compensation: (1465, 7)
Performance: (1465, 7)
Experience: (1465, 8)
Employment Status: (1465, 3)

In [22]:
hr_data = pd.merge(employees, compensation, on='EmployeeNumber')

hr_data.shape

(1465, 20)

In [23]:

hr_data = pd.merge(hr_data, performance, on='EmployeeNumber')
hr_data = pd.merge(hr_data, experience, on='EmployeeNumber')
hr_data = pd.merge(hr_data, employment_status, on='EmployeeNumber')

hr_data.shape

(1465, 35)

In [25]:
# Check categorical columns for inconsistent values

for column in ['Gender', 'MaritalStatus', 'EducationField',
               'Department', 'JobRole', 'BusinessTravel',
               'Attrition', 'OverTime']:
    print(column)
    print(hr_data[column].value_counts())
    print("--------------------")

Gender
Gender
Male       875
Female     585
  Male       1
Male         1
Femal        1
M            1
m            1
Name: count, dtype: int64
--------------------
MaritalStatus
MaritalStatus
Married     670
Single      468
Divorced    327
Name: count, dtype: int64
--------------------
EducationField
EducationField
Life Sciences       603
Medical             464
Marketing           158
Technical Degree    131
Other                82
Human Resources      27
Name: count, dtype: int64
--------------------
Department
Department
Research & Development    958
Sales                     445
Human Resources            62
Name: count, dtype: int64
--------------------
JobRole
JobRole
Sales Executive              325
Research Scientist           291
Laboratory Technician        257
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               51
Name: count, dtype: int64
--------------------
BusinessTravel
BusinessTravel
Travel_Rarely        1039
Travel_Frequently     276
Non-Travel            150
Name: count, dtype: int64
--------------------
Attrition
Attrition
No     1228
Yes     237
Name: count, dtype: int64
--------------------
OverTime
OverTime
No     1049
Yes     416
Name: count, dtype: int64
--------------------

In [26]:
# Remove extra spaces
hr_data['Gender'] = hr_data['Gender'].str.strip()

# Correct inconsistent entries
hr_data['Gender'] = hr_data['Gender'].replace({
    'Femal': 'Female',
    'M': 'Male',
    'm': 'Male'
})

# Check results
print(hr_data['Gender'].value_counts())

Gender
Male      879
Female    586
Name: count, dtype: int64